"""Open a GitHub auto-fix PR from a set of FilePatches using PyGithub."""

from __future__ import annotations

import time

import structlog

from autopr.patch_generator import FilePatch, apply_patch_to_text
from scanner import config
from scanner.models import SecurityFinding

log = structlog.get_logger(__name__)

PR_BODY_TEMPLATE = """## 🛡️ TerraGuard Auto-Fix

This PR was automatically generated to remediate security regressions
detected in #{original_pr_number}.

### Regressions Fixed

| Resource | Rule | Benchmark | Change |
|---|---|---|---|
{table_rows}

### Review Checklist
- [ ] Verify the fix does not break existing functionality
- [ ] Confirm the remediation matches your architecture intent
- [ ] Run `terraform plan` locally to validate

> Generated by TerraGuard · [View Dashboard]({dashboard_url})
"""

AUTOFIX_LABEL = "terraguard-autofix"


def _table_rows(
    patches: list[FilePatch], findings_by_rule: dict[str, SecurityFinding]
) -> str:
    rows = []
    for p in patches:
        f = findings_by_rule.get(p.rule_id)
        benchmark = ", ".join(f.benchmark_controls) if f else "—"
        change = (
            f.remediation if f and f.remediation else "Security fix applied"
        ).strip()
        rows.append(f"| `{p.resource}` | `{p.rule_id}` | {benchmark} | {change} |")
    return "\n".join(rows)


def create_fix_pr(
    base_branch: str,
    patches: list[FilePatch],
    findings: list[SecurityFinding],
    original_pr_number: int,
) -> str | None:
    """Create a branch, apply patches, and open a PR targeting `base_branch`.

    Returns the PR URL, or None if disabled / no token / no patches.
    """
    if not config.ENABLE_AUTO_FIX_PR:
        log.info("autofix_disabled")
        return None
    if not config.GITHUB_TOKEN:
        log.warning("autofix_no_token")
        return None
    if not patches:
        log.info("autofix_no_patches")
        return None

    from github import Github, GithubException

    gh = Github(config.GITHUB_TOKEN)
    repo = gh.get_repo(config.REPO)

    fix_branch = f"terraguard/fix-{original_pr_number}-{int(time.time())}"
    base = repo.get_branch(base_branch)
    repo.create_git_ref(ref=f"refs/heads/{fix_branch}", sha=base.commit.sha)
    log.info("autofix_branch_created", branch=fix_branch, base=base_branch)

    # Group patches by file so each file is committed once.
    by_file: dict[str, list[FilePatch]] = {}
    for p in patches:
        by_file.setdefault(p.file_path, []).append(p)

    for file_path, file_patches in by_file.items():
        try:
            contents = repo.get_contents(file_path, ref=fix_branch)
        except GithubException:
            log.warning("autofix_file_missing", file=file_path)
            continue
        text = contents.decoded_content.decode("utf-8")
        for p in file_patches:
            try:
                text = apply_patch_to_text(text, p)
            except ValueError as exc:
                log.warning("autofix_patch_skip", error=str(exc))
        repo.update_file(
            path=file_path,
            message=f"fix(security): remediate {len(file_patches)} TerraGuard regression(s)",
            content=text,
            sha=contents.sha,
            branch=fix_branch,
        )
        log.info("autofix_file_committed", file=file_path)

    findings_by_rule = {f.rule_id: f for f in findings}
    body = PR_BODY_TEMPLATE.format(
        original_pr_number=original_pr_number,
        table_rows=_table_rows(patches, findings_by_rule),
        dashboard_url=config.DASHBOARD_URL,
    )

    pr = repo.create_pull(
        title=f"fix(security): remediate {len(patches)} TerraGuard regression(s)",
        body=body,
        base=base_branch,
        head=fix_branch,
    )
    try:
        pr.add_to_labels(AUTOFIX_LABEL)
    except GithubException:
        log.warning("autofix_label_failed", label=AUTOFIX_LABEL)

    log.info("autofix_pr_opened", url=pr.html_url)
    return pr.html_url
